### ISSUE TITLE
Update Team Members

### ISSUE THREAD

**Issue by titusfortner** [watir/watir.github.io#38]
I added myself. Who else? @abaird?
I'll reach out to orde who is very active on Stack Overflow.

**Comment by jkotests** [comment]
The following should be moved to the alumni list:
- [Željko Filipin](https://groups.google.com/forum/#!topic/watir-development/UVprmRKc0aM)

**Comment by jarmo** [comment]
You can move me also to alumni list because I haven't been active lately and don't see it happening anytime soon as well.

But before doing that please update my avatar to [this](https://www.gravatar.com/avatar/d3d2f2138083612189fd819deb77ad21.jpg?s=78&d=wavatar) and change description to **Code monkey for Watir 1.x – 5.x, watir-rails and watir-rspec gems.**

Thanks.

**Comment by abaird** [comment]
I'm not sure if I've done enough work to justify being a team member.
