### ISSUE TITLE
3rd Party Gems

### ISSUE THREAD

**Issue by titusfortner** [watir/watir.github.io#52]
Where do we want to document 3rd Party gems? On the website or in github readme?

I noticed there are a bunch [here](https://github.com/watir/watir_meta) that should be put somewhere else one way or another.

**Comment by jarmo** [comment]
Usually README and front page of a project are the same to keep things in sync and have same information available. That's how I would approach this problem.

However, since https://watir.github.io has menu structure and everything I would have a separate menu entry for gems like these and put the same gems into README as they were previously so that they're easy to find.

**Comment by titusfortner** [comment]
http://watir.com/add-ons/
